// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/reentry-legal/DarkLegalTech.tsx": () => import("../components/mockups/reentry-legal/DarkLegalTech.tsx"),
  "./components/mockups/reentry-legal/ModernGradient.tsx": () => import("../components/mockups/reentry-legal/ModernGradient.tsx"),
  "./components/mockups/reentry-legal/WarmAccessible.tsx": () => import("../components/mockups/reentry-legal/WarmAccessible.tsx")
};
